-- MySQL Script generated by MySQL Workbench
-- Sun 10 Jan 2021 09:44:59 AM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema craiglist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `craiglist` ;

-- -----------------------------------------------------
-- Schema craiglist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `craiglist` ;
USE `craiglist` ;

-- -----------------------------------------------------
-- Table `craiglist`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `craiglist`.`regions` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craiglist`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `craiglist`.`locations` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `regions_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `regions_id`),
  INDEX `fk_locations_regions1_idx` (`regions_id` ASC) VISIBLE,
  CONSTRAINT `fk_locations_regions1`
    FOREIGN KEY (`regions_id`)
    REFERENCES `craiglist`.`regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craiglist`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `craiglist`.`categories` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craiglist`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `craiglist`.`users` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craiglist`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `craiglist`.`posts` (
  `id` BIGINT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `text` TEXT NULL,
  `locations_id` BIGINT NOT NULL,
  `categories_id` BIGINT NOT NULL,
  `users_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `locations_id`, `categories_id`, `users_id`),
  INDEX `fk_posts_locations_idx` (`locations_id` ASC) VISIBLE,
  INDEX `fk_posts_categories1_idx` (`categories_id` ASC) VISIBLE,
  INDEX `fk_posts_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_locations`
    FOREIGN KEY (`locations_id`)
    REFERENCES `craiglist`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `craiglist`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `craiglist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
