-- MySQL Script generated by MySQL Workbench
-- Sun 10 Jan 2021 10:17:14 AM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema soccer_league
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `soccer_league` ;

-- -----------------------------------------------------
-- Schema soccer_league
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soccer_league` ;
USE `soccer_league` ;

-- -----------------------------------------------------
-- Table `soccer_league`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccer_league`.`teams` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccer_league`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccer_league`.`games` (
  `id` BIGINT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccer_league`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccer_league`.`players` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NULL,
  `teams_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `teams_id`),
  CONSTRAINT `fk_players_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `soccer_league`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_players_teams1_idx` ON `soccer_league`.`players` (`teams_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `soccer_league`.`referees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccer_league`.`referees` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccer_league`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccer_league`.`matches` (
  `id` BIGINT NOT NULL,
  `teams_id` BIGINT NOT NULL,
  `games_id` BIGINT NOT NULL,
  `referees_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `teams_id`, `games_id`, `referees_id`),
  CONSTRAINT `fk_teams_games_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `soccer_league`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teams_games_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `soccer_league`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_referees1`
    FOREIGN KEY (`referees_id`)
    REFERENCES `soccer_league`.`referees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_teams_games_teams1_idx` ON `soccer_league`.`matches` (`teams_id` ASC) VISIBLE;

CREATE INDEX `fk_teams_games_games1_idx` ON `soccer_league`.`matches` (`games_id` ASC) VISIBLE;

CREATE INDEX `fk_matches_referees1_idx` ON `soccer_league`.`matches` (`referees_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `soccer_league`.`goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccer_league`.`goals` (
  `id` BIGINT NOT NULL,
  `number` INT NULL,
  `players_id` BIGINT NOT NULL,
  `matches_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `players_id`, `matches_id`),
  CONSTRAINT `fk_goals_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `soccer_league`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goals_matches1`
    FOREIGN KEY (`matches_id`)
    REFERENCES `soccer_league`.`matches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_goals_players1_idx` ON `soccer_league`.`goals` (`players_id` ASC) VISIBLE;

CREATE INDEX `fk_goals_matches1_idx` ON `soccer_league`.`goals` (`matches_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
